UPDATE sys_maintenance_order SET facility_guy_id = '101' WHERE facility_guys_name = '黄志均';
UPDATE sys_maintenance_order SET facility_guy_id = '102' WHERE facility_guys_name = '罗锟杨';
UPDATE sys_maintenance_order SET facility_guy_id = '103' WHERE facility_guys_name = '林嘉玮';
UPDATE sys_maintenance_order SET facility_guy_id = '104' WHERE facility_guys_name = '黎广标';
UPDATE sys_maintenance_order SET facility_guy_id = '105' WHERE facility_guys_name = '廖来运';
UPDATE sys_maintenance_order SET facility_guy_id = '106' WHERE facility_guys_name = '谢海平';
UPDATE sys_maintenance_order SET facility_guy_id = '107' WHERE facility_guys_name = '龙锦溪';
UPDATE sys_maintenance_order SET facility_guy_id = '108' WHERE facility_guys_name = '杨志聪';
UPDATE sys_maintenance_order SET facility_guy_id = '109' WHERE facility_guys_name = 'Test';
